### ISSUE TITLE
express optional sub-model function that determines volume

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_lang#5]
Needed by cell-cycle model

**Comment by jonrkarr** [comment]
Can you elaborate on what you'd like?

**Comment by jonrkarr** [comment]
Done in 898c1b6358e93591d3d5af103f89f48072a78979. Volume is now a function of a compartment mass and density. `density`, `density_units`, `volume`, and `volume_units` are attributes of `Compartment`. `density` is a float. `volume` is a expression which is constrained to be the product of the total mass of the species in the compartment and the density of the compartment.

The initial volume is determined by
1. Sample the concentration of each species from their initial distributions
2. Sum the mass of the species in each compartment
3. Use the density of each compartment to calculate their volumes

Note, one small issue with this formulation is that as models become more detailed and more species are added to the model, the total mass of each compartment will increase, causing the calculated volume of each compartment to increase with successive iterations of models (assuming the density is set to the experimentally observed density of cells and held constant over successive iterations of models). Assuming that water is represented in the model, adding additional species in successive versions will only increase the total mass of each compartment by a small amount because the composition of cells is dominated by water. In this formulation, the only way to avoid this issue is to decrease the density with each successive revision of the model by setting the density to the density of the represented species in cells. This would cause the density parameter to be different than the experimentally observed density of cells.
